name: lint-compliance-test

on:
  push:
    # todo ensure that env vars are promoted via side channel
    branches: [main]

concurrency: ${{ github.workflow }}

jobs:
  lint:
    name: "lint"
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: lint
        working-directory: ./orchestration/
        run: |
          echo "todo implement lint"
#            ${GITHUB_WORKSPACE}/scripts/tf.sh init test test-fake
#            ${GITHUB_WORKSPACE}/scripts/tf.sh lint test test-fake

  compliance:
    name: "compliance"
    needs: lint
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: compliance
        working-directory: ./implementation/
        run: |
          ${GITHUB_WORKSPACE}/scripts/tf.sh sec test test-fake

  test:
    needs: compliance
    name: "test"
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: tests
        run: echo "todo implement tests"
